import {baseUrl} from "./index";
export const getAnswersByQuestionTestPlayerUrl: string = baseUrl + "SAnswer/getAnswersByQuestion/";
export const checkSAnswerUrl: string = baseUrl + "SAnswer/checkAnswers";
export const getTimeStampUrl: string = baseUrl + "TestPlayer/getTimeStamp";
export const saveEndTimeUrl: string = baseUrl + "TestPlayer/saveEndTime";
export const getEndTimeUrl: string = baseUrl + "TestPlayer/getEndTime";
export const resetSessionDataUrl: string = baseUrl + "TestPlayer/resetSessionData";
export const getTestRecordUrl: string = baseUrl + "test/getRecords/";
export const countTestPassesByStudentUrl: string = baseUrl + "Result/countTestPassesByStudent/";
export const navButtonConstClassName: string = "btn nom-qua";